### ISSUE TITLE
Comfortable with GoFiber framework?

### ISSUE THREAD

**Issue by shahriar350** [olahol/melody#68]
I am working with GoFiber. I feel comfortable seeing this WebSocket framework. Can I use this in my GoFiber application?

**Comment by olahol** [comment]
FastHTTP is not supported by `gorilla/websocket`-

**Comment by idc77** [comment]
fasthttp/websocket is a fork of gorilla/websocket.
What are the odds this might be adapted?

**Comment by codecat** [comment]
I did a super quick hacky fork of Melody because I needed it to work with Fiber as well: https://github.com/codecat/melody

Definitely not gonna be maintaining it as much (I also removed the tests because I didn't wanna rewrite all of those), but it's usable in its current state, if anyone needs it.

```go
api.Get("/live", func(c *fiber.Ctx) error {
	return gMelody.HandleRequest(c.Context())
})
```
